name: build
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install pylint
    - name: Lint with Pylint
      run: |
        pylint $(git ls-files '*.py')
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('requirements.txt') }}
    - name: Install unit test dependencies
      run: |
        pip install wheel
        pip install -r requirements.txt
        pip install mysqlclient coverage lxml_html_clean
        cp .ci.settings.py dmoj/local_settings.py
    - name: Start MySQL
      run: sudo systemctl start mysql.service
    - name: Run unit tests
      run: coverage run --source=. manage.py test judge
  styles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node 22
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: Install npm packages
        run: npm install -g sass postcss-cli postcss autoprefixer
      - name: Install TailwindCSS
        run: npm install tailwindcss
      - name: Build style.css
        run: ./make_style.sh
